[workspace]
name = "mpc_qpbenchmark"
channels = ["conda-forge", "gurobi"]
platforms = ["linux-64"]

[dependencies]
clarabel = ">=0.4.1"
cvxopt = ">=1.3.0"
daqp = ">=0.5.1"
ecos = ">=2.0.10"
gurobi = ">=11.0.3"
ipython = "*"
jaxopt = "*"
kvxopt = "*"
matplotlib = "*"
numpy = ">=1.25.2"
osqp = ">=0.6.2"
piqp = ">=0.2.2"
proxsuite = ">=0.4.1"
python = ">=3.10"
qpbenchmark = ">=2.4.0"
quadprog = ">=0.1.11"
scs = ">=3.2.2"

[pypi-dependencies]
highspy = ">=1.5.2"
qpalm = ">=1.2.1"
qpax = "*"

[tasks]
mpc_qpbenchmark = "python ./mpc_qpbenchmark.py run"
mpc_qpbenchmark-dense = "python ./mpc_qpbenchmark_dense.py run"
mpc_qpbenchmark-sparse = "python ./mpc_qpbenchmark_sparse.py run"

[tasks.mpc_qpbenchmark-all]
depends-on = [
    "mpc_qpbenchmark",
    "mpc_qpbenchmark-dense",
    "mpc_qpbenchmark-sparse",
]
